use crate::get_data_dir;
use crate::mcp_runtime::{compose_mcp_tool_name, McpClient, McpToolCallOutput};
use chrono::{Datelike, Timelike, Weekday};
use regex::Regex;
use reqwest::header::{HeaderMap, HeaderName, HeaderValue, AUTHORIZATION};
use serde::{Deserialize, Serialize};
use serde_json::{json, Map, Value};
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::PathBuf;
use std::sync::{Mutex, OnceLock};
use std::time::{SystemTime, UNIX_EPOCH};
use tauri::Emitter;

include!("ai_assistant/types.rs");
include!("ai_assistant/state.rs");
include!("ai_assistant/settings.rs");
include!("ai_assistant/tools.rs");
include!("ai_assistant/providers.rs");
include!("ai_assistant/conversations.rs");
include!("ai_assistant/schedules.rs");
include!("ai_assistant/model_request.rs");
include!("ai_assistant/scheduler.rs");
include!("ai_assistant/commands.rs");
include!("ai_assistant/tests.rs");
