mod ai_assistant;
mod ai_env;
mod ai_news;
mod ai_sessions;
mod app_store;
mod assistant_mcp;
mod backup;
mod claude_profiles;
mod cli_probe;
mod cli_updates;
mod config;
mod config_conflict;
mod crypto;
mod git;
mod managed_assets;
mod mcp_export;
mod mcp_runtime;
mod mcp_servers;
mod mcp_templates;
mod messages;
mod protocol_router;
mod proxy;
mod runtime_profiles;
mod secrets;
mod skills;
mod ssh_tunnels;
mod storage;
mod subagents;
mod version_detect;
mod workflows;
mod workspaces;

use serde::{Deserialize, Serialize};
use std::fs::{self, File};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Duration;

include!("lib/windows_data.rs");
include!("lib/oauth_open.rs");
include!("lib/ssh_oauth.rs");
include!("lib/runtime_services.rs");
include!("lib/cli.rs");
include!("lib/shortcuts_tray.rs");
include!("lib/run_app.rs");
