use reqwest::Client;
use serde::{Deserialize, Serialize};
use serde_json::{json, Map, Value};
use std::collections::HashMap;
use std::fs;
use std::io::ErrorKind;
use std::path::PathBuf;
use std::sync::{Mutex, OnceLock};
use std::time::{Instant, SystemTime, UNIX_EPOCH};
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::{TcpListener, TcpStream};
use tokio::sync::oneshot;

include!("protocol_router/types_config.rs");
include!("protocol_router/commands.rs");
include!("protocol_router/runtime_http.rs");
include!("protocol_router/conversion.rs");
include!("protocol_router/responses_sse.rs");
include!("protocol_router/stats_public.rs");
include!("protocol_router/tests.rs");
