use crate::config::{self, StorageConfig, SubagentSourceConfig};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Component, Path, PathBuf};
use std::process::Command;
use std::sync::{Mutex, OnceLock, TryLockError};
use std::time::{SystemTime, UNIX_EPOCH};
use toml_edit::{self, DocumentMut, Item, Table};

include!("subagents/types.rs");
include!("subagents/paths_state.rs");
include!("subagents/repository.rs");
include!("subagents/catalog_parse.rs");
include!("subagents/diff.rs");
include!("subagents/sync_apply.rs");
include!("subagents/installed_scan.rs");
include!("subagents/commands.rs");
include!("subagents/tests.rs");
